//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://SuperErdogan.org/")]
public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getTxtFileOperationCompleted;
    
    private System.Threading.SendOrPostCallback getAllFileNamesOperationCompleted;
    
    private System.Threading.SendOrPostCallback ChangeTxtFileOperationCompleted;
    
    /// <remarks/>
    public WebService() {
        this.Url = "http://localhost:53269/WebService.asmx";
    }
    
    /// <remarks/>
    public event getTxtFileCompletedEventHandler getTxtFileCompleted;
    
    /// <remarks/>
    public event getAllFileNamesCompletedEventHandler getAllFileNamesCompleted;
    
    /// <remarks/>
    public event ChangeTxtFileCompletedEventHandler ChangeTxtFileCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SuperErdogan.org/getTxtFile", RequestNamespace="http://SuperErdogan.org/", ResponseNamespace="http://SuperErdogan.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getTxtFile(string filename) {
        object[] results = this.Invoke("getTxtFile", new object[] {
                    filename});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTxtFile(string filename, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTxtFile", new object[] {
                    filename}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetTxtFile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getTxtFileAsync(string filename) {
        this.getTxtFileAsync(filename, null);
    }
    
    /// <remarks/>
    public void getTxtFileAsync(string filename, object userState) {
        if ((this.getTxtFileOperationCompleted == null)) {
            this.getTxtFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTxtFileOperationCompleted);
        }
        this.InvokeAsync("getTxtFile", new object[] {
                    filename}, this.getTxtFileOperationCompleted, userState);
    }
    
    private void OngetTxtFileOperationCompleted(object arg) {
        if ((this.getTxtFileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTxtFileCompleted(this, new getTxtFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SuperErdogan.org/getAllFileNames", RequestNamespace="http://SuperErdogan.org/", ResponseNamespace="http://SuperErdogan.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] getAllFileNames() {
        object[] results = this.Invoke("getAllFileNames", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllFileNames(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllFileNames", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndgetAllFileNames(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void getAllFileNamesAsync() {
        this.getAllFileNamesAsync(null);
    }
    
    /// <remarks/>
    public void getAllFileNamesAsync(object userState) {
        if ((this.getAllFileNamesOperationCompleted == null)) {
            this.getAllFileNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllFileNamesOperationCompleted);
        }
        this.InvokeAsync("getAllFileNames", new object[0], this.getAllFileNamesOperationCompleted, userState);
    }
    
    private void OngetAllFileNamesOperationCompleted(object arg) {
        if ((this.getAllFileNamesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAllFileNamesCompleted(this, new getAllFileNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SuperErdogan.org/ChangeTxtFile", RequestNamespace="http://SuperErdogan.org/", ResponseNamespace="http://SuperErdogan.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void ChangeTxtFile(string fileText, string filename) {
        this.Invoke("ChangeTxtFile", new object[] {
                    fileText,
                    filename});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginChangeTxtFile(string fileText, string filename, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ChangeTxtFile", new object[] {
                    fileText,
                    filename}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndChangeTxtFile(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void ChangeTxtFileAsync(string fileText, string filename) {
        this.ChangeTxtFileAsync(fileText, filename, null);
    }
    
    /// <remarks/>
    public void ChangeTxtFileAsync(string fileText, string filename, object userState) {
        if ((this.ChangeTxtFileOperationCompleted == null)) {
            this.ChangeTxtFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeTxtFileOperationCompleted);
        }
        this.InvokeAsync("ChangeTxtFile", new object[] {
                    fileText,
                    filename}, this.ChangeTxtFileOperationCompleted, userState);
    }
    
    private void OnChangeTxtFileOperationCompleted(object arg) {
        if ((this.ChangeTxtFileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ChangeTxtFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getTxtFileCompletedEventHandler(object sender, getTxtFileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTxtFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTxtFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getAllFileNamesCompletedEventHandler(object sender, getAllFileNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAllFileNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAllFileNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ChangeTxtFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
